// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package sticker

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker(in *jlexer.Lexer, out *StickerPackDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "slug":
			if in.IsNull() {
				in.Skip()
				out.Slug = nil
			} else {
				if out.Slug == nil {
					out.Slug = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Slug = string(in.String())
				}
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "thumbnail_url":
			if in.IsNull() {
				in.Skip()
				out.ThumbnailURL = nil
			} else {
				if out.ThumbnailURL == nil {
					out.ThumbnailURL = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ThumbnailURL = string(in.String())
				}
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "stickers":
			if in.IsNull() {
				in.Skip()
				out.Stickers = nil
			} else {
				in.Delim('[')
				if out.Stickers == nil {
					if !in.IsDelim(']') {
						out.Stickers = make([]StickerDTO, 0, 1)
					} else {
						out.Stickers = []StickerDTO{}
					}
				} else {
					out.Stickers = (out.Stickers)[:0]
				}
				for !in.IsDelim(']') {
					var v1 StickerDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Stickers = append(out.Stickers, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker(out *jwriter.Writer, in StickerPackDTO) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Slug != nil {
		const prefix string = ",\"slug\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Slug))
	}
	{
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Title))
	}
	if in.ThumbnailURL != nil {
		const prefix string = ",\"thumbnail_url\":"
		out.RawString(prefix)
		out.String(string(*in.ThumbnailURL))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"stickers\":"
		out.RawString(prefix)
		if in.Stickers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Stickers {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StickerPackDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StickerPackDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StickerPackDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StickerPackDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker1(in *jlexer.Lexer, out *StickerDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "slug":
			if in.IsNull() {
				in.Skip()
				out.Slug = nil
			} else {
				if out.Slug == nil {
					out.Slug = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Slug = string(in.String())
				}
			}
		case "emoji":
			if in.IsNull() {
				in.Skip()
				out.Emoji = nil
			} else {
				if out.Emoji == nil {
					out.Emoji = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Emoji = string(in.String())
				}
			}
		case "file_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FileURL = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "pack_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PackID = int64(in.Int64())
			}
		case "width":
			if in.IsNull() {
				in.Skip()
				out.Width = nil
			} else {
				if out.Width == nil {
					out.Width = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Width = int(in.Int())
				}
			}
		case "height":
			if in.IsNull() {
				in.Skip()
				out.Height = nil
			} else {
				if out.Height == nil {
					out.Height = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Height = int(in.Int())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker1(out *jwriter.Writer, in StickerDTO) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Slug != nil {
		const prefix string = ",\"slug\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Slug))
	}
	if in.Emoji != nil {
		const prefix string = ",\"emoji\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Emoji))
	}
	{
		const prefix string = ",\"file_url\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FileURL))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"pack_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.PackID))
	}
	if in.Width != nil {
		const prefix string = ",\"width\":"
		out.RawString(prefix)
		out.Int(int(*in.Width))
	}
	if in.Height != nil {
		const prefix string = ",\"height\":"
		out.RawString(prefix)
		out.Int(int(*in.Height))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StickerDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StickerDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StickerDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StickerDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker1(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker2(in *jlexer.Lexer, out *ResponseGetStickerPacks) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "packs":
			if in.IsNull() {
				in.Skip()
				out.Packs = nil
			} else {
				in.Delim('[')
				if out.Packs == nil {
					if !in.IsDelim(']') {
						out.Packs = make([]StickerPackDTO, 0, 0)
					} else {
						out.Packs = []StickerPackDTO{}
					}
				} else {
					out.Packs = (out.Packs)[:0]
				}
				for !in.IsDelim(']') {
					var v4 StickerPackDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Packs = append(out.Packs, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker2(out *jwriter.Writer, in ResponseGetStickerPacks) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"packs\":"
		out.RawString(prefix[1:])
		if in.Packs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Packs {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseGetStickerPacks) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseGetStickerPacks) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseGetStickerPacks) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseGetStickerPacks) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoSticker2(l, v)
}
