CREATE TABLE chats (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type TEXT NOT NULL,
    title TEXT,
    description TEXT,
    owner_id BIGINT,
    avatar_url TEXT,
    last_message_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);