CREATE TABLE complaint (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status TEXT NOT NULL,
    type TEXT NOT NULL,
    feedback_name TEXT NOT NULL,
    feedback_email TEXT NOT NULL,
    body TEXT NOT NULL,
    user_id BIGINT,
    attachment_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE complaint
    ADD CONSTRAINT fk_complaint_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
