CREATE TABLE payments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    payment_id TEXT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    amount INTEGER NOT NULL,
    subscription_days INTEGER NOT NULL,
    payment_url TEXT,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_payments_user_id ON payments (user_id);
