CREATE TYPE message_attachment_type AS ENUM ('photo', 'video', 'file', 'contact');

CREATE TABLE message_attachments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    type message_attachment_type NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    file_url TEXT,
    file_name TEXT,
    mime_type TEXT,
    file_size BIGINT,
    contact_user_id BIGINT,
    contact_first_name TEXT,
    contact_last_name TEXT,
    contact_avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_message_attachments_message_id ON message_attachments (message_id, sort_order);

ALTER TABLE messages
DROP CONSTRAINT IF EXISTS chk_messages_content;

-- PostgreSQL does not allow subqueries in CHECK constraints.
-- Attachment-only messages always get a preview string in application code (see buildAttachmentPreview).
ALTER TABLE messages
ADD CONSTRAINT chk_messages_content
CHECK (deleted_at IS NOT NULL OR content IS NOT NULL OR sticker_id IS NOT NULL);
