ALTER TABLE sticker_packs
ADD COLUMN IF NOT EXISTS slug TEXT,
ADD COLUMN IF NOT EXISTS title TEXT,
ADD COLUMN IF NOT EXISTS thumbnail_url TEXT,
ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;

ALTER TABLE stickers
ADD COLUMN IF NOT EXISTS slug TEXT,
ADD COLUMN IF NOT EXISTS emoji TEXT,
ADD COLUMN IF NOT EXISTS width INT,
ADD COLUMN IF NOT EXISTS height INT,
ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_sticker_packs_slug
ON sticker_packs(slug)
WHERE slug IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_stickers_pack_slug
ON stickers(pack_id, slug)
WHERE slug IS NOT NULL;
