run:
  timeout: 5m

#Список включаемых линтеров
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - typecheck

    - gofmt         #Проверяет форматирование
    - goimports     #Проверяет порядок импортов
    - misspell      #Ищет опечатки в комментариях/строковых литералах

    - gocyclo       #Проверяет цикломатическую сложность функций
    - gocognit      #Когнитивная сложность

    - depguard      #Запрещает импорт определенных пакетов (чтобы слой repo не импортил handler)
    - importas      #Позволяет унифицировать имена импортов (чтобы везде одинаково назывались)
    - nilnil        #Проверяет, что функции возвращающие nil возвращают и ошибку

    - gosec         #Проверяет уязвимости (иньекции, утечки)
    - prealloc      #Советы по предварительному выделению слайсов

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: "Устарел, используйте io или os пакеты"
  gocyclo:
    min-complexity: 15 #Если функция сложнее 15 будет ругаться
  gocognit:
    min-complexity: 20
  govet:
    enable-all: true
  goimports:
    local-prefixes: github.com/go-park-mail-ru/2026_1_ASAP

issues:
  exclude-dirs:
    - bin
    - vendor
    - tmp
    - .git
  exclude-rules:
    #Исключаем тесты из некоторых проверок 
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - errcheck
    #Исключаем G101 (hardcoded credentials) для файлов с кодами ошибок
    - path: internal/dto/api/response.go
      linters:
        - gosec
      text: "G101"