services:
  gateway:
    build:
      context: .
      dockerfile: ./docker/gateway.Dockerfile
    env_file:
      - ./.env
    environment:
      CONFIG_PATH: configs/gateway/local.yml
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - profile
    restart: always

  media:
    build:
      context: .
      dockerfile: ./docker/media.Dockerfile
    env_file:
      - ./.env
    environment:
      CONFIG_PATH: configs/media/local.yml
    ports:
      - "8003:8003"
    depends_on:
      - db
      - migrate
      - minio
    restart: always

  profile:
    build:
      context: .
      dockerfile: ./docker/profile.Dockerfile
    env_file:
      - ./.env
    environment:
      CONFIG_PATH: configs/profile/local.yml
    ports:
      - "8002:8002"
    depends_on:
      - db
      - migrate
      - minio
    restart: always

  auth:
    build:
      context: .
      dockerfile: ./docker/auth.Dockerfile
      args:
        SERVICE_NAME: auth
    env_file:
      - ./.env
    environment:
      CONFIG_PATH: configs/auth/local.yml
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - db
      - migrate
      - minio
    restart: always

  redis:
    image: redis:latest
    env_file:
      - ./.env
    environment:
      REDIS_PORT: "6379"
    ports:
      - "6379:6379"
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$$REDIS_PASSWORD"
    restart: always

  db:
    image: postgres:15
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: asap
    ports:
      - "5432:5432"
    restart: always

  migrate:
    image: migrate/migrate
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: asap
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        RETRIES=10
        until migrate -path=/migrations -database="postgres://$$POSTGRES_USER:$$POSTGRES_PASSWORD@db:5432/$$POSTGRES_DB?sslmode=disable" up || [ $$RETRIES -eq 0 ]; do
          echo "Migration failed, retrying in 3s..."
          RETRIES=$$((RETRIES-1))
          sleep 3
        done
    depends_on:
      - db
    restart: "no"

  minio:
    image: minio/minio:latest
    env_file:
      - ./.env
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

volumes:
  minio_data: