// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package profile

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile(in *jlexer.Lexer, out *RequestUpdateName) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "last_name":
			if in.IsNull() {
				in.Skip()
				out.LastName = nil
			} else {
				if out.LastName == nil {
					out.LastName = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.LastName = string(in.String())
				}
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile(out *jwriter.Writer, in RequestUpdateName) {
	out.RawByte('{')
	first := true
	_ = first
	if in.LastName != nil {
		const prefix string = ",\"last_name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.LastName))
	}
	{
		const prefix string = ",\"first_name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FirstName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestUpdateName) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestUpdateName) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestUpdateName) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestUpdateName) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile(l, v)
}
func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile1(in *jlexer.Lexer, out *RequestUpdateLogin) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "login":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Login = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile1(out *jwriter.Writer, in RequestUpdateLogin) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix[1:])
		out.String(string(in.Login))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestUpdateLogin) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestUpdateLogin) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestUpdateLogin) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestUpdateLogin) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile1(l, v)
}
func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile2(in *jlexer.Lexer, out *RequestUpdateEmail) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile2(out *jwriter.Writer, in RequestUpdateEmail) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestUpdateEmail) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestUpdateEmail) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestUpdateEmail) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestUpdateEmail) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile2(l, v)
}
func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile3(in *jlexer.Lexer, out *RequestUpdateBirthDate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "birth_date":
			if in.IsNull() {
				in.Skip()
				out.BirthDate = nil
			} else {
				if out.BirthDate == nil {
					out.BirthDate = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.BirthDate = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile3(out *jwriter.Writer, in RequestUpdateBirthDate) {
	out.RawByte('{')
	first := true
	_ = first
	if in.BirthDate != nil {
		const prefix string = ",\"birth_date\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.BirthDate))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestUpdateBirthDate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestUpdateBirthDate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestUpdateBirthDate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestUpdateBirthDate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile3(l, v)
}
func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile4(in *jlexer.Lexer, out *RequestUpdateBio) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Bio = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile4(out *jwriter.Writer, in RequestUpdateBio) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Bio))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestUpdateBio) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestUpdateBio) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestUpdateBio) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestUpdateBio) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile4(l, v)
}
func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile5(in *jlexer.Lexer, out *RequestUpdateAvatarURL) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvatarURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile5(out *jwriter.Writer, in RequestUpdateAvatarURL) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.AvatarURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestUpdateAvatarURL) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestUpdateAvatarURL) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestUpdateAvatarURL) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestUpdateAvatarURL) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile5(l, v)
}
func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile6(in *jlexer.Lexer, out *RequestSearchIdByLogin) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "login":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Login = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile6(out *jwriter.Writer, in RequestSearchIdByLogin) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix[1:])
		out.String(string(in.Login))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestSearchIdByLogin) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestSearchIdByLogin) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestSearchIdByLogin) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestSearchIdByLogin) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile6(l, v)
}
func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile7(in *jlexer.Lexer, out *RequestCreateProfile) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "profile_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProfileID = int64(in.Int64())
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile7(out *jwriter.Writer, in RequestCreateProfile) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"profile_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ProfileID))
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestCreateProfile) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestCreateProfile) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestCreateProfile) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestCreateProfile) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoProfile7(l, v)
}
