package chat

import (
	"errors"
)

var (
	ErrChatNotFound                      = errors.New("Chat not found")
	ErrChatAlreadyExists                 = errors.New("Chat already exists")
	ErrNoMessage                         = errors.New("No message in chat")
	ErrNotMember                         = errors.New("User is not member of this chat")
	ErrDialogAlreadyExists               = errors.New("dialog already exists between these users")
	ErrCantCreateDialogWithYourself      = errors.New("you cant create dialog with yourself")
	ErrDialogMustHave2Users              = errors.New("dialog must have only 2 users")
	ErrOnlyOwnerCanDeleteChat            = errors.New("Only owner of the chat can delete chat")
	ErrMessageEmpty                      = errors.New("Message is empty")
	ErrMessageTooLong                    = errors.New("Message is too long")
	ErrMessageNotMember                  = errors.New("Message sender is not member of this chat")
	ErrDialogCannotHaveCustomAvatar      = errors.New("Cant change avatar in dialog")
	ErrDialogCannotHaveCustomTitle       = errors.New("Cant change title in dialog")
	ErrOnlyOwnerCanAddPeople             = errors.New("Only owner of chat can add people to chat")
	ErrMemberAlreadyInChat               = errors.New("Member you try to add already in chat")
	ErrCantAddMemberToDialog             = errors.New("You cant add member in your dialog chat")
	ErrUserNotFound                      = errors.New("user not found")
	ErrMemberNotFound                    = errors.New("Not found member you want to delete")
	ErrOnlyOwnerCanDeletePeople          = errors.New("Only owner of chat can delete people from chat")
	ErrCantDeleteMemberFromDialog        = errors.New("You cant delete member from your dialog chat")
	ErrCantDeleteOwnerOfChat             = errors.New("You cant delete owner of chat from the chat")
	ErrUserNotMember                     = errors.New("User you try to delete is not member of this chat")
	ErrCantQuitDialog                    = errors.New("You cant quit dialog")
	ErrOwnerCantQuitGroup                = errors.New("As owner you cant quit group")
	ErrOnlyOwnerCanSendMessaage          = errors.New("Only owner can send message in this chat")
	ErrOnlyOwnerCanChangeAvatar          = errors.New("Only owner can change avatar")
	ErrOnlyOwnerCanChangeTitle           = errors.New("Only owner can change title")
	ErrCantEditMessage                   = errors.New("You cant edit this message")
	ErrCanJoinOnlyChannel                = errors.New("you can join only channel")
	ErrAlreadyInChat                     = errors.New("you already in chat you try to join")
	ErrOnlyOwnerCanChangeDescription     = errors.New("Only owner can change description")
	ErrDialogCannotHaveCustomDescription = errors.New("Cant change desription in dialog")
	ErrReadMessageInvalid                = errors.New("invalid message for read cursor")
	ErrInvalidAttachment                 = errors.New("invalid attachment")
	ErrAttachmentNotOwned                = errors.New("attachment not owned by user")
	ErrContactNotFound                   = errors.New("contact not found")
	ErrTooManyAttachments                = errors.New("too many attachments")
	ErrAttachmentForbidden               = errors.New("attachment access forbidden")
	ErrStickerNotFound                   = errors.New("sticker not found")
	ErrInvalidSticker                    = errors.New("invalid sticker")
	ErrSubscriptionRequired              = errors.New("subscription required")
	ErrNotVoiceMessage                   = errors.New("message has no voice attachment")
	ErrTranscriptionFailed               = errors.New("voice transcription failed")
)
