// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat(in *jlexer.Lexer, out *ResponseGetChatMembers) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "members_id":
			if in.IsNull() {
				in.Skip()
				out.MembersId = nil
			} else {
				in.Delim('[')
				if out.MembersId == nil {
					if !in.IsDelim(']') {
						out.MembersId = make([]int64, 0, 8)
					} else {
						out.MembersId = []int64{}
					}
				} else {
					out.MembersId = (out.MembersId)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = int64(in.Int64())
					}
					out.MembersId = append(out.MembersId, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat(out *jwriter.Writer, in ResponseGetChatMembers) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"members_id\":"
		out.RawString(prefix[1:])
		if in.MembersId == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.MembersId {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseGetChatMembers) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseGetChatMembers) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseGetChatMembers) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseGetChatMembers) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat(l, v)
}
func easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat1(in *jlexer.Lexer, out *RequestUpdateTitle) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat1(out *jwriter.Writer, in RequestUpdateTitle) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestUpdateTitle) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestUpdateTitle) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestUpdateTitle) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestUpdateTitle) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat1(l, v)
}
func easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat2(in *jlexer.Lexer, out *RequestUpdateDescription) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat2(out *jwriter.Writer, in RequestUpdateDescription) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix[1:])
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestUpdateDescription) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestUpdateDescription) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestUpdateDescription) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestUpdateDescription) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat2(l, v)
}
func easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat3(in *jlexer.Lexer, out *RequestJoinChannel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int64(in.Int64())
			}
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatId = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat3(out *jwriter.Writer, in RequestJoinChannel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserId))
	}
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ChatId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestJoinChannel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestJoinChannel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestJoinChannel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestJoinChannel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat3(l, v)
}
func easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat4(in *jlexer.Lexer, out *RequestDeleteMember) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "member_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MemberId = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat4(out *jwriter.Writer, in RequestDeleteMember) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"member_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.MemberId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestDeleteMember) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestDeleteMember) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestDeleteMember) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestDeleteMember) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat4(l, v)
}
func easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat5(in *jlexer.Lexer, out *RequestAddMember) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "members_id":
			if in.IsNull() {
				in.Skip()
				out.MembersId = nil
			} else {
				in.Delim('[')
				if out.MembersId == nil {
					if !in.IsDelim(']') {
						out.MembersId = make([]int64, 0, 8)
					} else {
						out.MembersId = []int64{}
					}
				} else {
					out.MembersId = (out.MembersId)[:0]
				}
				for !in.IsDelim(']') {
					var v4 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = int64(in.Int64())
					}
					out.MembersId = append(out.MembersId, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat5(out *jwriter.Writer, in RequestAddMember) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"members_id\":"
		out.RawString(prefix[1:])
		if in.MembersId == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.MembersId {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestAddMember) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestAddMember) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestAddMember) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestAddMember) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat5(l, v)
}
func easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat6(in *jlexer.Lexer, out *MessageDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "sender_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderId = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat6(out *jwriter.Writer, in MessageDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix[1:])
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"sender_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.SenderId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MessageDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MessageDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MessageDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MessageDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat6(l, v)
}
func easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat7(in *jlexer.Lexer, out *ChatInformationDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "avatar":
			if in.IsNull() {
				in.Skip()
				out.Avatar = nil
			} else {
				if out.Avatar == nil {
					out.Avatar = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Avatar = string(in.String())
				}
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "chat_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatType = ChatType(in.String())
			}
		case "last_message":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.LastMessage).UnmarshalEasyJSON(in)
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "owner_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OwnerID = int64(in.Int64())
			}
		case "unread_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnreadCount = int64(in.Int64())
			}
		case "last_read_message_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastReadMessageID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat7(out *jwriter.Writer, in ChatInformationDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"avatar\":"
		out.RawString(prefix[1:])
		if in.Avatar == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Avatar))
		}
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"chat_type\":"
		out.RawString(prefix)
		out.String(string(in.ChatType))
	}
	{
		const prefix string = ",\"last_message\":"
		out.RawString(prefix)
		(in.LastMessage).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"owner_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.OwnerID))
	}
	{
		const prefix string = ",\"unread_count\":"
		out.RawString(prefix)
		out.Int64(int64(in.UnreadCount))
	}
	{
		const prefix string = ",\"last_read_message_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastReadMessageID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChatInformationDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChatInformationDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChatInformationDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChatInformationDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat7(l, v)
}
func easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat8(in *jlexer.Lexer, out *ChatCreate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = ChatType(in.String())
			}
		case "members_id":
			if in.IsNull() {
				in.Skip()
				out.MembersID = nil
			} else {
				in.Delim('[')
				if out.MembersID == nil {
					if !in.IsDelim(']') {
						out.MembersID = make([]int64, 0, 8)
					} else {
						out.MembersID = []int64{}
					}
				} else {
					out.MembersID = (out.MembersID)[:0]
				}
				for !in.IsDelim(']') {
					var v7 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = int64(in.Int64())
					}
					out.MembersID = append(out.MembersID, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat8(out *jwriter.Writer, in ChatCreate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"members_id\":"
		out.RawString(prefix)
		if in.MembersID == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.MembersID {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v9))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChatCreate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChatCreate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea69964EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChatCreate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChatCreate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea69964DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoChat8(l, v)
}
