// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package complaint

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson608421a4DecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint(in *jlexer.Lexer, out *RequestUpdateComplaintStatus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "complaint_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ComplaintId = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = ComplaintStatus(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson608421a4EncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint(out *jwriter.Writer, in RequestUpdateComplaintStatus) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"complaint_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ComplaintId))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestUpdateComplaintStatus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson608421a4EncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestUpdateComplaintStatus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson608421a4EncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestUpdateComplaintStatus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson608421a4DecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestUpdateComplaintStatus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson608421a4DecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint(l, v)
}
func easyjson608421a4DecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint1(in *jlexer.Lexer, out *RequestGetComplaints) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson608421a4EncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint1(out *jwriter.Writer, in RequestGetComplaints) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestGetComplaints) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson608421a4EncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestGetComplaints) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson608421a4EncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestGetComplaints) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson608421a4DecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestGetComplaints) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson608421a4DecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint1(l, v)
}
func easyjson608421a4DecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint2(in *jlexer.Lexer, out *RequestGetComplaint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "complaint_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ComplaintId = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson608421a4EncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint2(out *jwriter.Writer, in RequestGetComplaint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"complaint_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ComplaintId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestGetComplaint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson608421a4EncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestGetComplaint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson608421a4EncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestGetComplaint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson608421a4DecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestGetComplaint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson608421a4DecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint2(l, v)
}
func easyjson608421a4DecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint3(in *jlexer.Lexer, out *FeedbackDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "feedback_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeedBackName = string(in.String())
			}
		case "feedback_email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeedBackEmail = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson608421a4EncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint3(out *jwriter.Writer, in FeedbackDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"feedback_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.FeedBackName))
	}
	{
		const prefix string = ",\"feedback_email\":"
		out.RawString(prefix)
		out.String(string(in.FeedBackEmail))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FeedbackDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson608421a4EncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FeedbackDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson608421a4EncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FeedbackDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson608421a4DecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FeedbackDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson608421a4DecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint3(l, v)
}
