// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package complaint

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint(in *jlexer.Lexer, out *ResponseGetComplaints) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "complaints":
			if in.IsNull() {
				in.Skip()
				out.Complaints = nil
			} else {
				in.Delim('[')
				if out.Complaints == nil {
					if !in.IsDelim(']') {
						out.Complaints = make([]ComplaintDTO, 0, 0)
					} else {
						out.Complaints = []ComplaintDTO{}
					}
				} else {
					out.Complaints = (out.Complaints)[:0]
				}
				for !in.IsDelim(']') {
					var v1 ComplaintDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Complaints = append(out.Complaints, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint(out *jwriter.Writer, in ResponseGetComplaints) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"complaints\":"
		out.RawString(prefix[1:])
		if in.Complaints == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Complaints {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseGetComplaints) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseGetComplaints) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseGetComplaints) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseGetComplaints) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint(l, v)
}
func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint1(in *jlexer.Lexer, out *ResponseGetComplaint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "complaint":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.ComplaintDTO).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint1(out *jwriter.Writer, in ResponseGetComplaint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"complaint\":"
		out.RawString(prefix[1:])
		(in.ComplaintDTO).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseGetComplaint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseGetComplaint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseGetComplaint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseGetComplaint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint1(l, v)
}
func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint2(in *jlexer.Lexer, out *ResponseCreateComplaint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "complaint":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.ComplaintDTO).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint2(out *jwriter.Writer, in ResponseCreateComplaint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"complaint\":"
		out.RawString(prefix[1:])
		(in.ComplaintDTO).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseCreateComplaint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseCreateComplaint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseCreateComplaint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseCreateComplaint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint2(l, v)
}
func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint3(in *jlexer.Lexer, out *ComplaintDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "feedback":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.FeedbackDTO).UnmarshalEasyJSON(in)
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "attachment_url":
			if in.IsNull() {
				in.Skip()
				out.AttachmentURL = nil
			} else {
				if out.AttachmentURL == nil {
					out.AttachmentURL = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AttachmentURL = string(in.String())
				}
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint3(out *jwriter.Writer, in ComplaintDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"feedback\":"
		out.RawString(prefix)
		(in.FeedbackDTO).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	if in.UserID != 0 {
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	if in.AttachmentURL != nil {
		const prefix string = ",\"attachment_url\":"
		out.RawString(prefix)
		out.String(string(*in.AttachmentURL))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ComplaintDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ComplaintDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ComplaintDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ComplaintDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoComplaint3(l, v)
}
