-- Initial DDL snapshot before DBMS HW 4 performance optimizations.
-- Source: current project migrations in db/migrations as of the start of the work.

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT,
    avatar_url TEXT,
    bio TEXT,
    birth_date DATE,
    last_seen TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE contacts (
    user_id BIGINT NOT NULL,
    contact_user_id BIGINT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (user_id, contact_user_id)
);

CREATE TABLE chat_types (
    type TEXT PRIMARY KEY
);

INSERT INTO chat_types(type)
VALUES
('dialog'),
('group'),
('channel');

CREATE TABLE chat_member_roles (
    role TEXT PRIMARY KEY
);

INSERT INTO chat_member_roles(role)
VALUES
('member'),
('admin'),
('owner');

CREATE TABLE chats (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type TEXT NOT NULL,
    title TEXT,
    description TEXT,
    owner_id BIGINT,
    avatar_url TEXT,
    last_message_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE chat_members (
    chat_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role TEXT NOT NULL,
    last_read_message_id BIGINT,
    joined_at TIMESTAMPTZ DEFAULT now(),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (chat_id, user_id)
);

CREATE TABLE sticker_packs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    slug TEXT,
    title TEXT,
    thumbnail_url TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE stickers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pack_id BIGINT NOT NULL,
    file_url TEXT NOT NULL,
    slug TEXT,
    emoji TEXT,
    width INT,
    height INT,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    chat_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content TEXT,
    sticker_id BIGINT,
    edited BOOLEAN DEFAULT FALSE,
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', COALESCE(content, ''))) STORED,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE attachments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message_id BIGINT NOT NULL,
    file_url TEXT NOT NULL,
    file_type TEXT,
    file_size BIGINT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE reactions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    emoji TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    type TEXT NOT NULL,
    entity_id BIGINT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE vk_accounts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    vk_user_id TEXT NOT NULL,
    vk_email TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE complaint (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status TEXT NOT NULL,
    type TEXT NOT NULL,
    feedback_name TEXT NOT NULL,
    feedback_email TEXT NOT NULL,
    body TEXT NOT NULL,
    user_id BIGINT,
    attachment_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE subscriptions (
    user_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    active BOOLEAN NOT NULL DEFAULT false,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE payments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    payment_id TEXT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    amount INTEGER NOT NULL,
    subscription_days INTEGER NOT NULL,
    payment_url TEXT,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TYPE message_attachment_type AS ENUM ('photo', 'video', 'file', 'contact', 'voice');

CREATE TABLE message_attachments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    type message_attachment_type NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    file_url TEXT,
    file_name TEXT,
    mime_type TEXT,
    file_size BIGINT,
    contact_user_id BIGINT,
    contact_first_name TEXT,
    contact_last_name TEXT,
    contact_avatar_url TEXT,
    duration_ms INT,
    waveform JSONB,
    transcript TEXT,
    is_capybara BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER TABLE contacts
ADD CONSTRAINT fk_contacts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE contacts
ADD CONSTRAINT fk_contacts_contact_user FOREIGN KEY (contact_user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE contacts
ADD CONSTRAINT chk_contacts_user_not_null CHECK (user_id IS NOT NULL AND contact_user_id IS NOT NULL);

ALTER TABLE chats
ADD CONSTRAINT fk_chats_type FOREIGN KEY (type) REFERENCES chat_types(type);

ALTER TABLE chats
ADD CONSTRAINT fk_chats_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE RESTRICT;

ALTER TABLE chats
ADD CONSTRAINT fk_chats_last_message FOREIGN KEY (last_message_id) REFERENCES messages(id) ON DELETE SET NULL;

ALTER TABLE chat_members
ADD CONSTRAINT fk_chat_members_chat FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE;

ALTER TABLE chat_members
ADD CONSTRAINT fk_chat_members_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE chat_members
ADD CONSTRAINT fk_chat_members_role FOREIGN KEY (role) REFERENCES chat_member_roles(role);

ALTER TABLE chat_members
ADD CONSTRAINT chk_chat_members_not_null CHECK (chat_id IS NOT NULL AND user_id IS NOT NULL AND role IS NOT NULL);

ALTER TABLE messages
ADD CONSTRAINT fk_messages_chat FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE;

ALTER TABLE messages
ADD CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id);

ALTER TABLE messages
ADD CONSTRAINT fk_messages_sticker FOREIGN KEY (sticker_id) REFERENCES stickers(id);

ALTER TABLE messages
ADD CONSTRAINT chk_messages_content
CHECK (deleted_at IS NOT NULL OR content IS NOT NULL OR sticker_id IS NOT NULL);

ALTER TABLE attachments
ADD CONSTRAINT fk_attachments_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;

ALTER TABLE attachments
ADD CONSTRAINT chk_attachments_not_null CHECK (message_id IS NOT NULL AND file_url IS NOT NULL);

ALTER TABLE reactions
ADD CONSTRAINT fk_reactions_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;

ALTER TABLE reactions
ADD CONSTRAINT fk_reactions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE reactions
ADD CONSTRAINT uq_reactions UNIQUE (message_id, user_id, emoji);

ALTER TABLE reactions
ADD CONSTRAINT chk_reactions_not_null CHECK (message_id IS NOT NULL AND user_id IS NOT NULL AND emoji IS NOT NULL);

ALTER TABLE stickers
ADD CONSTRAINT fk_stickers_pack FOREIGN KEY (pack_id) REFERENCES sticker_packs(id) ON DELETE CASCADE;

ALTER TABLE stickers
ADD CONSTRAINT chk_stickers_not_null CHECK (pack_id IS NOT NULL AND file_url IS NOT NULL);

ALTER TABLE notifications
ADD CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE notifications
ADD CONSTRAINT chk_notifications_not_null CHECK (user_id IS NOT NULL AND type IS NOT NULL);

ALTER TABLE chat_members
ADD CONSTRAINT fk_chat_members_last_read FOREIGN KEY (last_read_message_id) REFERENCES messages(id) ON DELETE SET NULL;

ALTER TABLE vk_accounts
ADD CONSTRAINT fk_vk_accounts_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE vk_accounts
ADD CONSTRAINT uq_vk_accounts_vk_user_id UNIQUE (vk_user_id);

ALTER TABLE complaint
ADD CONSTRAINT fk_complaint_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE INDEX idx_messages_search_vector_gin
ON messages USING GIN (search_vector)
WHERE deleted_at IS NULL;

CREATE INDEX idx_messages_chat_id_id_desc
ON messages (chat_id, id DESC)
WHERE deleted_at IS NULL;

CREATE INDEX idx_profiles_first_name_trgm
ON profiles USING GIN (first_name gin_trgm_ops);

CREATE INDEX idx_profiles_last_name_trgm
ON profiles USING GIN (last_name gin_trgm_ops);

CREATE INDEX idx_users_login_trgm
ON users USING GIN (login gin_trgm_ops);

CREATE INDEX idx_chats_title_trgm
ON chats USING GIN (title gin_trgm_ops)
WHERE title IS NOT NULL;

CREATE INDEX idx_payments_user_id ON payments (user_id);

CREATE INDEX idx_message_attachments_message_id ON message_attachments (message_id, sort_order);

CREATE UNIQUE INDEX uq_sticker_packs_slug
ON sticker_packs(slug)
WHERE slug IS NOT NULL;

CREATE UNIQUE INDEX uq_stickers_pack_slug
ON stickers(pack_id, slug)
WHERE slug IS NOT NULL;

