server:
  host: 0.0.0.0
  port: "8001"

session:
  ttl_seconds: 3600

redis:
  host: redis
  port: "6379"
  database: 0

profile:
  grpc_addr: profile:8002

postgres:
  host: db
  port: "5432"
  user: postgres
  db: asap

s3:
  host: minio
  port: "9000"
  bucket: media
  use_ssl: false
  public_use_ssl: false
  public_host: pulseapp.space
  public_port: "9000"

app:
  shutdown_seconds: 10
  log_level: info

vkid:
  client_id: test-client-id
  redirect_uri: https://pulseapp.space/api/v1/auth/vk
  auth_url: https://id.vk.ru/oauth2/auth
  public_info_url: https://id.vk.ru/oauth2/public_info
