server:
  host: 0.0.0.0
  port: "8010"

postgres:
  host: db
  port: "5432"
  user: postgres
  db: asap

redis:
  host: redis
  port: "6379"
  database: 0

app:
  shutdown_seconds: 10
  log_level: info
