// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package vision

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson82a45abeDecodeGithubComGoParkMailRu20261ASAPInternalMediaVision(in *jlexer.Lexer, out *ReadyResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ready":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Ready = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson82a45abeEncodeGithubComGoParkMailRu20261ASAPInternalMediaVision(out *jwriter.Writer, in ReadyResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ready\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Ready))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReadyResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson82a45abeEncodeGithubComGoParkMailRu20261ASAPInternalMediaVision(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReadyResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson82a45abeEncodeGithubComGoParkMailRu20261ASAPInternalMediaVision(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReadyResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson82a45abeDecodeGithubComGoParkMailRu20261ASAPInternalMediaVision(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReadyResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson82a45abeDecodeGithubComGoParkMailRu20261ASAPInternalMediaVision(l, v)
}
func easyjson82a45abeDecodeGithubComGoParkMailRu20261ASAPInternalMediaVision1(in *jlexer.Lexer, out *DetectResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "is_capybara":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsCapybara = bool(in.Bool())
			}
		case "score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Score = float64(in.Float64())
			}
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Error = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson82a45abeEncodeGithubComGoParkMailRu20261ASAPInternalMediaVision1(out *jwriter.Writer, in DetectResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"is_capybara\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.IsCapybara))
	}
	{
		const prefix string = ",\"score\":"
		out.RawString(prefix)
		out.Float64(float64(in.Score))
	}
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DetectResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson82a45abeEncodeGithubComGoParkMailRu20261ASAPInternalMediaVision1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DetectResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson82a45abeEncodeGithubComGoParkMailRu20261ASAPInternalMediaVision1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DetectResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson82a45abeDecodeGithubComGoParkMailRu20261ASAPInternalMediaVision1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DetectResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson82a45abeDecodeGithubComGoParkMailRu20261ASAPInternalMediaVision1(l, v)
}
func easyjson82a45abeDecodeGithubComGoParkMailRu20261ASAPInternalMediaVision2(in *jlexer.Lexer, out *DetectRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "image_path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ImagePath = string(in.String())
			}
		case "threshold":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Threshold = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson82a45abeEncodeGithubComGoParkMailRu20261ASAPInternalMediaVision2(out *jwriter.Writer, in DetectRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"image_path\":"
		out.RawString(prefix[1:])
		out.String(string(in.ImagePath))
	}
	{
		const prefix string = ",\"threshold\":"
		out.RawString(prefix)
		out.Float64(float64(in.Threshold))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DetectRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson82a45abeEncodeGithubComGoParkMailRu20261ASAPInternalMediaVision2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DetectRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson82a45abeEncodeGithubComGoParkMailRu20261ASAPInternalMediaVision2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DetectRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson82a45abeDecodeGithubComGoParkMailRu20261ASAPInternalMediaVision2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DetectRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson82a45abeDecodeGithubComGoParkMailRu20261ASAPInternalMediaVision2(l, v)
}
