// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package message

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6b1ea713DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(in *jlexer.Lexer, out *messageAttachmentWire) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "url":
			if in.IsNull() {
				in.Skip()
				out.URL = nil
			} else {
				if out.URL == nil {
					out.URL = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.URL = string(in.String())
				}
			}
		case "file_name":
			if in.IsNull() {
				in.Skip()
				out.FileName = nil
			} else {
				if out.FileName == nil {
					out.FileName = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.FileName = string(in.String())
				}
			}
		case "mime_type":
			if in.IsNull() {
				in.Skip()
				out.MimeType = nil
			} else {
				if out.MimeType == nil {
					out.MimeType = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MimeType = string(in.String())
				}
			}
		case "file_size":
			if in.IsNull() {
				in.Skip()
				out.FileSize = nil
			} else {
				if out.FileSize == nil {
					out.FileSize = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.FileSize = int64(in.Int64())
				}
			}
		case "duration_ms":
			if in.IsNull() {
				in.Skip()
				out.DurationMs = nil
			} else {
				if out.DurationMs == nil {
					out.DurationMs = new(int32)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.DurationMs = int32(in.Int32())
				}
			}
		case "waveform":
			if in.IsNull() {
				in.Skip()
				out.Waveform = nil
			} else {
				out.Waveform = in.Bytes()
			}
		case "transcript":
			if in.IsNull() {
				in.Skip()
				out.Transcript = nil
			} else {
				if out.Transcript == nil {
					out.Transcript = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Transcript = string(in.String())
				}
			}
		case "can_transcribe":
			if in.IsNull() {
				in.Skip()
				out.CanTranscribe = nil
			} else {
				if out.CanTranscribe == nil {
					out.CanTranscribe = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.CanTranscribe = bool(in.Bool())
				}
			}
		case "contact_user_id":
			if in.IsNull() {
				in.Skip()
				out.ContactUserID = nil
			} else {
				if out.ContactUserID == nil {
					out.ContactUserID = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ContactUserID = int64(in.Int64())
				}
			}
		case "contact_first_name":
			if in.IsNull() {
				in.Skip()
				out.ContactFirstName = nil
			} else {
				if out.ContactFirstName == nil {
					out.ContactFirstName = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ContactFirstName = string(in.String())
				}
			}
		case "contact_last_name":
			if in.IsNull() {
				in.Skip()
				out.ContactLastName = nil
			} else {
				if out.ContactLastName == nil {
					out.ContactLastName = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ContactLastName = string(in.String())
				}
			}
		case "contact_avatar_url":
			if in.IsNull() {
				in.Skip()
				out.ContactAvatarURL = nil
			} else {
				if out.ContactAvatarURL == nil {
					out.ContactAvatarURL = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ContactAvatarURL = string(in.String())
				}
			}
		case "is_blur":
			if in.IsNull() {
				in.Skip()
				out.IsBlur = nil
			} else {
				if out.IsBlur == nil {
					out.IsBlur = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.IsBlur = bool(in.Bool())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6b1ea713EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(out *jwriter.Writer, in messageAttachmentWire) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.URL != nil {
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(*in.URL))
	}
	if in.FileName != nil {
		const prefix string = ",\"file_name\":"
		out.RawString(prefix)
		out.String(string(*in.FileName))
	}
	if in.MimeType != nil {
		const prefix string = ",\"mime_type\":"
		out.RawString(prefix)
		out.String(string(*in.MimeType))
	}
	if in.FileSize != nil {
		const prefix string = ",\"file_size\":"
		out.RawString(prefix)
		out.Int64(int64(*in.FileSize))
	}
	if in.DurationMs != nil {
		const prefix string = ",\"duration_ms\":"
		out.RawString(prefix)
		out.Int32(int32(*in.DurationMs))
	}
	if len(in.Waveform) != 0 {
		const prefix string = ",\"waveform\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Waveform)
	}
	if in.Transcript != nil {
		const prefix string = ",\"transcript\":"
		out.RawString(prefix)
		out.String(string(*in.Transcript))
	}
	if in.CanTranscribe != nil {
		const prefix string = ",\"can_transcribe\":"
		out.RawString(prefix)
		out.Bool(bool(*in.CanTranscribe))
	}
	if in.ContactUserID != nil {
		const prefix string = ",\"contact_user_id\":"
		out.RawString(prefix)
		out.Int64(int64(*in.ContactUserID))
	}
	if in.ContactFirstName != nil {
		const prefix string = ",\"contact_first_name\":"
		out.RawString(prefix)
		out.String(string(*in.ContactFirstName))
	}
	if in.ContactLastName != nil {
		const prefix string = ",\"contact_last_name\":"
		out.RawString(prefix)
		out.String(string(*in.ContactLastName))
	}
	if in.ContactAvatarURL != nil {
		const prefix string = ",\"contact_avatar_url\":"
		out.RawString(prefix)
		out.String(string(*in.ContactAvatarURL))
	}
	if in.IsBlur != nil {
		const prefix string = ",\"is_blur\":"
		out.RawString(prefix)
		out.Bool(bool(*in.IsBlur))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v messageAttachmentWire) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6b1ea713EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v messageAttachmentWire) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6b1ea713EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *messageAttachmentWire) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6b1ea713DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *messageAttachmentWire) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6b1ea713DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(l, v)
}
