// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package message

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(in *jlexer.Lexer, out *UploadAttachmentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "attachment_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AttachmentURL = string(in.String())
			}
		case "object_key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ObjectKey = string(in.String())
			}
		case "mime_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MimeType = string(in.String())
			}
		case "file_size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FileSize = int64(in.Int64())
			}
		case "file_name":
			if in.IsNull() {
				in.Skip()
				out.FileName = nil
			} else {
				if out.FileName == nil {
					out.FileName = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.FileName = string(in.String())
				}
			}
		case "duration_ms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DurationMs = int32(in.Int32())
			}
		case "waveform":
			if in.IsNull() {
				in.Skip()
				out.Waveform = nil
			} else {
				out.Waveform = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(out *jwriter.Writer, in UploadAttachmentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"attachment_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.AttachmentURL))
	}
	if in.ObjectKey != "" {
		const prefix string = ",\"object_key\":"
		out.RawString(prefix)
		out.String(string(in.ObjectKey))
	}
	{
		const prefix string = ",\"mime_type\":"
		out.RawString(prefix)
		out.String(string(in.MimeType))
	}
	{
		const prefix string = ",\"file_size\":"
		out.RawString(prefix)
		out.Int64(int64(in.FileSize))
	}
	if in.FileName != nil {
		const prefix string = ",\"file_name\":"
		out.RawString(prefix)
		out.String(string(*in.FileName))
	}
	if in.DurationMs != 0 {
		const prefix string = ",\"duration_ms\":"
		out.RawString(prefix)
		out.Int32(int32(in.DurationMs))
	}
	if len(in.Waveform) != 0 {
		const prefix string = ",\"waveform\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Waveform)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UploadAttachmentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UploadAttachmentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UploadAttachmentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UploadAttachmentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(l, v)
}
func easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(in *jlexer.Lexer, out *ResponseVoiceTranscript) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "message_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MessageID = int64(in.Int64())
			}
		case "attachment_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AttachmentID = int64(in.Int64())
			}
		case "transcript":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Transcript = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(out *jwriter.Writer, in ResponseVoiceTranscript) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatID))
	}
	{
		const prefix string = ",\"message_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.MessageID))
	}
	{
		const prefix string = ",\"attachment_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.AttachmentID))
	}
	{
		const prefix string = ",\"transcript\":"
		out.RawString(prefix)
		out.String(string(in.Transcript))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseVoiceTranscript) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseVoiceTranscript) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseVoiceTranscript) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseVoiceTranscript) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(l, v)
}
func easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(in *jlexer.Lexer, out *RequestTranscribeVoice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "message_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MessageID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(out *jwriter.Writer, in RequestTranscribeVoice) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatID))
	}
	{
		const prefix string = ",\"message_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.MessageID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestTranscribeVoice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestTranscribeVoice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestTranscribeVoice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestTranscribeVoice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(l, v)
}
func easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(in *jlexer.Lexer, out *RequestSendMessageAttachments) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "attachments":
			if in.IsNull() {
				in.Skip()
				out.Attachments = nil
			} else {
				in.Delim('[')
				if out.Attachments == nil {
					if !in.IsDelim(']') {
						out.Attachments = make([]AttachmentInput, 0, 1)
					} else {
						out.Attachments = []AttachmentInput{}
					}
				} else {
					out.Attachments = (out.Attachments)[:0]
				}
				for !in.IsDelim(']') {
					var v4 AttachmentInput
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Attachments = append(out.Attachments, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(out *jwriter.Writer, in RequestSendMessageAttachments) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatID))
	}
	if in.Text != "" {
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"attachments\":"
		out.RawString(prefix)
		if in.Attachments == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Attachments {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestSendMessageAttachments) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestSendMessageAttachments) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestSendMessageAttachments) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestSendMessageAttachments) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(l, v)
}
func easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(in *jlexer.Lexer, out *AttachmentInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		case "file_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FileName = string(in.String())
			}
		case "contact_user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContactUserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(out *jwriter.Writer, in AttachmentInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.URL != "" {
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	if in.FileName != "" {
		const prefix string = ",\"file_name\":"
		out.RawString(prefix)
		out.String(string(in.FileName))
	}
	if in.ContactUserID != 0 {
		const prefix string = ",\"contact_user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ContactUserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AttachmentInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AttachmentInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson76362c5bEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AttachmentInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AttachmentInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson76362c5bDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(l, v)
}
