// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package message

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(in *jlexer.Lexer, out *RequestSendSticker) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "sticker_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StickerID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(out *jwriter.Writer, in RequestSendSticker) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatID))
	}
	{
		const prefix string = ",\"sticker_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.StickerID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestSendSticker) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestSendSticker) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestSendSticker) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestSendSticker) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(l, v)
}
func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(in *jlexer.Lexer, out *RequestSendMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(out *jwriter.Writer, in RequestSendMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ChatID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestSendMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestSendMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestSendMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestSendMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(l, v)
}
func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(in *jlexer.Lexer, out *RequestMarkRead) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MessageID = int64(in.Int64())
			}
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(out *jwriter.Writer, in RequestMarkRead) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.MessageID))
	}
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ChatID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestMarkRead) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestMarkRead) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestMarkRead) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestMarkRead) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(l, v)
}
func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(in *jlexer.Lexer, out *RequestGetMessages) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "before_id":
			if in.IsNull() {
				in.Skip()
				out.BeforeID = nil
			} else {
				if out.BeforeID == nil {
					out.BeforeID = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.BeforeID = int64(in.Int64())
				}
			}
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(out *jwriter.Writer, in RequestGetMessages) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"before_id\":"
		out.RawString(prefix[1:])
		if in.BeforeID == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.BeforeID))
		}
	}
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ChatID))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestGetMessages) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestGetMessages) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestGetMessages) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestGetMessages) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(l, v)
}
func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(in *jlexer.Lexer, out *RequestEditMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "message_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MessageID = int64(in.Int64())
			}
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(out *jwriter.Writer, in RequestEditMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"message_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.MessageID))
	}
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ChatID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestEditMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestEditMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestEditMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestEditMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(l, v)
}
func easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage5(in *jlexer.Lexer, out *RequestDeleteMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MessageID = int64(in.Int64())
			}
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage5(out *jwriter.Writer, in RequestDeleteMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.MessageID))
	}
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ChatID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestDeleteMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestDeleteMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestDeleteMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestDeleteMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage5(l, v)
}
