// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package message

import (
	json "encoding/json"
	sticker "github.com/go-park-mail-ru/2026_1_ASAP/internal/chat/dto/sticker"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(in *jlexer.Lexer, out *ResponseSendMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "sender_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderID = int64(in.Int64())
			}
		case "temp_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TempID = string(in.String())
			}
		case "edited":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Edited = bool(in.Bool())
			}
		case "read":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Read = bool(in.Bool())
			}
		case "attachments":
			if in.IsNull() {
				in.Skip()
				out.Attachments = nil
			} else {
				in.Delim('[')
				if out.Attachments == nil {
					if !in.IsDelim(']') {
						out.Attachments = make([]MessageAttachmentDTO, 0, 0)
					} else {
						out.Attachments = []MessageAttachmentDTO{}
					}
				} else {
					out.Attachments = (out.Attachments)[:0]
				}
				for !in.IsDelim(']') {
					var v1 MessageAttachmentDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Attachments = append(out.Attachments, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "sticker":
			if in.IsNull() {
				in.Skip()
				out.Sticker = nil
			} else {
				if out.Sticker == nil {
					out.Sticker = new(sticker.StickerDTO)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Sticker).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(out *jwriter.Writer, in ResponseSendMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix[1:])
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ChatID))
	}
	{
		const prefix string = ",\"sender_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.SenderID))
	}
	if in.TempID != "" {
		const prefix string = ",\"temp_id\":"
		out.RawString(prefix)
		out.String(string(in.TempID))
	}
	{
		const prefix string = ",\"edited\":"
		out.RawString(prefix)
		out.Bool(bool(in.Edited))
	}
	{
		const prefix string = ",\"read\":"
		out.RawString(prefix)
		out.Bool(bool(in.Read))
	}
	if len(in.Attachments) != 0 {
		const prefix string = ",\"attachments\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v2, v3 := range in.Attachments {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Sticker != nil {
		const prefix string = ",\"sticker\":"
		out.RawString(prefix)
		(*in.Sticker).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseSendMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseSendMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseSendMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseSendMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage(l, v)
}
func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(in *jlexer.Lexer, out *ResponseMarkRead) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "reader_user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReaderUserID = int64(in.Int64())
			}
		case "last_read_message_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastReadMessageID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(out *jwriter.Writer, in ResponseMarkRead) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatID))
	}
	{
		const prefix string = ",\"reader_user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ReaderUserID))
	}
	{
		const prefix string = ",\"last_read_message_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastReadMessageID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseMarkRead) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseMarkRead) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseMarkRead) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseMarkRead) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage1(l, v)
}
func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(in *jlexer.Lexer, out *ResponseGetMessages) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "next_before_id":
			if in.IsNull() {
				in.Skip()
				out.NextBeforeID = nil
			} else {
				if out.NextBeforeID == nil {
					out.NextBeforeID = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.NextBeforeID = int64(in.Int64())
				}
			}
		case "messages":
			if in.IsNull() {
				in.Skip()
				out.Messages = nil
			} else {
				in.Delim('[')
				if out.Messages == nil {
					if !in.IsDelim(']') {
						out.Messages = make([]MessageDTO, 0, 0)
					} else {
						out.Messages = []MessageDTO{}
					}
				} else {
					out.Messages = (out.Messages)[:0]
				}
				for !in.IsDelim(']') {
					var v4 MessageDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Messages = append(out.Messages, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "has_more":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HasMore = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(out *jwriter.Writer, in ResponseGetMessages) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"next_before_id\":"
		out.RawString(prefix[1:])
		if in.NextBeforeID == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.NextBeforeID))
		}
	}
	{
		const prefix string = ",\"messages\":"
		out.RawString(prefix)
		if in.Messages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Messages {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"has_more\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasMore))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseGetMessages) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseGetMessages) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseGetMessages) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseGetMessages) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage2(l, v)
}
func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(in *jlexer.Lexer, out *ResponseEditMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "sender_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderID = int64(in.Int64())
			}
		case "edited":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Edited = bool(in.Bool())
			}
		case "read":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Read = bool(in.Bool())
			}
		case "last_message_edited":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastMessageEdited = bool(in.Bool())
			}
		case "last_message":
			if in.IsNull() {
				in.Skip()
				out.LastMessage = nil
			} else {
				if out.LastMessage == nil {
					out.LastMessage = new(LastMessageDTO)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.LastMessage).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(out *jwriter.Writer, in ResponseEditMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix[1:])
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ChatID))
	}
	{
		const prefix string = ",\"sender_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.SenderID))
	}
	{
		const prefix string = ",\"edited\":"
		out.RawString(prefix)
		out.Bool(bool(in.Edited))
	}
	{
		const prefix string = ",\"read\":"
		out.RawString(prefix)
		out.Bool(bool(in.Read))
	}
	{
		const prefix string = ",\"last_message_edited\":"
		out.RawString(prefix)
		out.Bool(bool(in.LastMessageEdited))
	}
	if in.LastMessage != nil {
		const prefix string = ",\"last_message\":"
		out.RawString(prefix)
		(*in.LastMessage).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseEditMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseEditMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseEditMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseEditMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage3(l, v)
}
func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(in *jlexer.Lexer, out *ResponseClearMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "sender_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderID = int64(in.Int64())
			}
		case "last_message_edited":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastMessageEdited = bool(in.Bool())
			}
		case "last_message":
			if in.IsNull() {
				in.Skip()
				out.LastMessage = nil
			} else {
				if out.LastMessage == nil {
					out.LastMessage = new(LastMessageDTO)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.LastMessage).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(out *jwriter.Writer, in ResponseClearMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ChatID))
	}
	{
		const prefix string = ",\"sender_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.SenderID))
	}
	{
		const prefix string = ",\"last_message_edited\":"
		out.RawString(prefix)
		out.Bool(bool(in.LastMessageEdited))
	}
	if in.LastMessage != nil {
		const prefix string = ",\"last_message\":"
		out.RawString(prefix)
		(*in.LastMessage).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseClearMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseClearMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseClearMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseClearMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage4(l, v)
}
func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage5(in *jlexer.Lexer, out *LastMessageDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "sender_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderId = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage5(out *jwriter.Writer, in LastMessageDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix[1:])
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"sender_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.SenderId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LastMessageDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LastMessageDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LastMessageDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LastMessageDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalChatDtoMessage5(l, v)
}
