// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package ws

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs(in *jlexer.Lexer, out *RequestPresenceTyping) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs(out *jwriter.Writer, in RequestPresenceTyping) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestPresenceTyping) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestPresenceTyping) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestPresenceTyping) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestPresenceTyping) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs(l, v)
}
func easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs1(in *jlexer.Lexer, out *PresenceUserPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs1(out *jwriter.Writer, in PresenceUserPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PresenceUserPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PresenceUserPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PresenceUserPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PresenceUserPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs1(l, v)
}
func easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs2(in *jlexer.Lexer, out *PresenceTypingPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "typing":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Typing = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs2(out *jwriter.Writer, in PresenceTypingPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"typing\":"
		out.RawString(prefix)
		out.Bool(bool(in.Typing))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PresenceTypingPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PresenceTypingPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PresenceTypingPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PresenceTypingPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs2(l, v)
}
func easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs3(in *jlexer.Lexer, out *PresenceLastSeenPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "last_seen_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.LastSeenAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs3(out *jwriter.Writer, in PresenceLastSeenPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"last_seen_at\":"
		out.RawString(prefix)
		out.Raw((in.LastSeenAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PresenceLastSeenPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PresenceLastSeenPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PresenceLastSeenPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PresenceLastSeenPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs3(l, v)
}
func easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs4(in *jlexer.Lexer, out *ChatUpdatedTitlePayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs4(out *jwriter.Writer, in ChatUpdatedTitlePayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChatUpdatedTitlePayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChatUpdatedTitlePayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChatUpdatedTitlePayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChatUpdatedTitlePayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs4(l, v)
}
func easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs5(in *jlexer.Lexer, out *ChatUpdatedMembersPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "updated_members_id":
			if in.IsNull() {
				in.Skip()
				out.UpdatedMembersID = nil
			} else {
				in.Delim('[')
				if out.UpdatedMembersID == nil {
					if !in.IsDelim(']') {
						out.UpdatedMembersID = make([]int64, 0, 8)
					} else {
						out.UpdatedMembersID = []int64{}
					}
				} else {
					out.UpdatedMembersID = (out.UpdatedMembersID)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = int64(in.Int64())
					}
					out.UpdatedMembersID = append(out.UpdatedMembersID, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs5(out *jwriter.Writer, in ChatUpdatedMembersPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"updated_members_id\":"
		out.RawString(prefix)
		if in.UpdatedMembersID == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.UpdatedMembersID {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v3))
			}
			out.RawByte(']')
		}
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChatUpdatedMembersPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChatUpdatedMembersPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChatUpdatedMembersPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChatUpdatedMembersPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs5(l, v)
}
func easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs6(in *jlexer.Lexer, out *ChatUpdatedDescriptionPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs6(out *jwriter.Writer, in ChatUpdatedDescriptionPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatID))
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(*in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChatUpdatedDescriptionPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChatUpdatedDescriptionPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChatUpdatedDescriptionPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChatUpdatedDescriptionPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs6(l, v)
}
func easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs7(in *jlexer.Lexer, out *ChatUpdatedAvatarPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatID = int64(in.Int64())
			}
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvatarURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs7(out *jwriter.Writer, in ChatUpdatedAvatarPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatID))
	}
	{
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		out.String(string(in.AvatarURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChatUpdatedAvatarPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChatUpdatedAvatarPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChatUpdatedAvatarPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChatUpdatedAvatarPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs7(l, v)
}
func easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs8(in *jlexer.Lexer, out *ChatDeletedPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs8(out *jwriter.Writer, in ChatDeletedPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChatDeletedPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChatDeletedPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF0ae8156EncodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChatDeletedPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChatDeletedPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF0ae8156DecodeGithubComGoParkMailRu20261ASAPInternalChatDtoWs8(l, v)
}
