// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package analytic

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic(in *jlexer.Lexer, out *ResponseComplaintAnalytic) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "count_status":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.CountStatus).UnmarshalEasyJSON(in)
			}
		case "count_type":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.CountType).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic(out *jwriter.Writer, in ResponseComplaintAnalytic) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"count_status\":"
		out.RawString(prefix[1:])
		(in.CountStatus).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"count_type\":"
		out.RawString(prefix)
		(in.CountType).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseComplaintAnalytic) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseComplaintAnalytic) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseComplaintAnalytic) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseComplaintAnalytic) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic(l, v)
}
func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic1(in *jlexer.Lexer, out *CountType) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "count_type_bug":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountBug = int64(in.Int64())
			}
		case "count_type_upgrade":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountUpgrade = int64(in.Int64())
			}
		case "count_type_product":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountProduct = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic1(out *jwriter.Writer, in CountType) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"count_type_bug\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.CountBug))
	}
	{
		const prefix string = ",\"count_type_upgrade\":"
		out.RawString(prefix)
		out.Int64(int64(in.CountUpgrade))
	}
	{
		const prefix string = ",\"count_type_product\":"
		out.RawString(prefix)
		out.Int64(int64(in.CountProduct))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CountType) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CountType) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CountType) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CountType) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic1(l, v)
}
func easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic2(in *jlexer.Lexer, out *CountStatus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "count_status_opened":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountStatusOpened = int64(in.Int64())
			}
		case "count_status_in_work":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountStatusInWork = int64(in.Int64())
			}
		case "count_status_closed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountStatusClosed = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic2(out *jwriter.Writer, in CountStatus) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"count_status_opened\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.CountStatusOpened))
	}
	{
		const prefix string = ",\"count_status_in_work\":"
		out.RawString(prefix)
		out.Int64(int64(in.CountStatusInWork))
	}
	{
		const prefix string = ",\"count_status_closed\":"
		out.RawString(prefix)
		out.Int64(int64(in.CountStatusClosed))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CountStatus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CountStatus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CountStatus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CountStatus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComGoParkMailRu20261ASAPInternalComplaintDtoAnalytic2(l, v)
}
