// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package contact

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4ee781cfDecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact(in *jlexer.Lexer, out *ResponseDeleteSuccess) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "contact_user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContactUserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ee781cfEncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact(out *jwriter.Writer, in ResponseDeleteSuccess) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contact_user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ContactUserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseDeleteSuccess) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ee781cfEncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseDeleteSuccess) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ee781cfEncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseDeleteSuccess) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ee781cfDecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseDeleteSuccess) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ee781cfDecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact(l, v)
}
func easyjson4ee781cfDecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact1(in *jlexer.Lexer, out *DeleteContactRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "contact_user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContactUserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ee781cfEncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact1(out *jwriter.Writer, in DeleteContactRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contact_user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ContactUserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeleteContactRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ee781cfEncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeleteContactRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ee781cfEncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeleteContactRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ee781cfDecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeleteContactRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ee781cfDecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact1(l, v)
}
func easyjson4ee781cfDecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact2(in *jlexer.Lexer, out *ContactResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "last_name":
			if in.IsNull() {
				in.Skip()
				out.LastName = nil
			} else {
				if out.LastName == nil {
					out.LastName = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.LastName = string(in.String())
				}
			}
		case "contact_avatar_url":
			if in.IsNull() {
				in.Skip()
				out.ContactAvatarUrl = nil
			} else {
				if out.ContactAvatarUrl == nil {
					out.ContactAvatarUrl = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ContactAvatarUrl = string(in.String())
				}
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "contact_user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContactUserID = int64(in.Int64())
			}
		case "is_online":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsOnline = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ee781cfEncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact2(out *jwriter.Writer, in ContactResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix[1:])
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	if in.LastName != nil {
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(*in.LastName))
	}
	{
		const prefix string = ",\"contact_avatar_url\":"
		out.RawString(prefix)
		if in.ContactAvatarUrl == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.ContactAvatarUrl))
		}
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"contact_user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ContactUserID))
	}
	{
		const prefix string = ",\"is_online\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsOnline))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ContactResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ee781cfEncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ContactResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ee781cfEncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ContactResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ee781cfDecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ContactResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ee781cfDecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact2(l, v)
}
func easyjson4ee781cfDecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact3(in *jlexer.Lexer, out *AddContactRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "last_name":
			if in.IsNull() {
				in.Skip()
				out.LastName = nil
			} else {
				if out.LastName == nil {
					out.LastName = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.LastName = string(in.String())
				}
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "contact_user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContactUserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ee781cfEncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact3(out *jwriter.Writer, in AddContactRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.LastName != nil {
		const prefix string = ",\"last_name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.LastName))
	}
	{
		const prefix string = ",\"first_name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"contact_user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ContactUserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddContactRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ee781cfEncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddContactRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ee781cfEncodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddContactRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ee781cfDecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddContactRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ee781cfDecodeGithubComGoParkMailRu20261ASAPInternalProfileDtoContact3(l, v)
}
