// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Аутентификация юзера с логином и паролем",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Логин пользователя",
                "parameters": [
                    {
                        "description": "Запрос на логин",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_auth.RequestLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseLoginSuccessForSwagger"
                        }
                    },
                    "400": {
                        "description": "Неправильный запрос или ошибка формата полей",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Некорректные данные логины",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Завершение сессии пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseLogoutSuccessForSwagger"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка выхода",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Создаёт нового пользователя с email и login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Запрос на регистрацию",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_auth.RequestRegistrate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseRegisterSuccessForSwagger"
                        }
                    },
                    "400": {
                        "description": "Неправильный запрос или ошибка формата полей",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "409": {
                        "description": "пользователь уже существует",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/chats": {
            "get": {
                "description": "Возвращает все чаты пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chats"
                ],
                "summary": "Получить список чатов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseGetChatsSuccessForSwagger"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Невозможно получить чаты",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт новый чат",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chats"
                ],
                "summary": "Создать чат",
                "parameters": [
                    {
                        "description": "Запрос на создание чата",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_chat.ChatCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseCreateChatSuccessForSwagger"
                        }
                    },
                    "400": {
                        "description": "Некорретный запрос или ошибка формата полей",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь неавторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка создания чата",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/chats/{chat_id}": {
            "get": {
                "description": "Возвращает информацию о чате",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chats"
                ],
                "summary": "Получить чат по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID чата",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseGetChatByIDSuccessForSwagger"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID чата",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь неавторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Чат не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутреняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/contacts": {
            "get": {
                "description": "Возвращает все контакты текущего пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contacts"
                ],
                "summary": "Получить список контактов",
                "responses": {
                    "200": {
                        "description": "Успешное получение списка контактов",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseGetContactsSuccessForSwagger"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Добавляет нового контакта в список контактов текущего пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contacts"
                ],
                "summary": "Создать контакт",
                "parameters": [
                    {
                        "description": "Запрос на создание контакта",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_contacts.AddContactRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Контакт успешно создан",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseCreateContactSuccessForSwagger"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос или ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Контакт уже существует",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/contacts/{contact_user_id}": {
            "delete": {
                "description": "Удаляет контакт из списка контактов текущего пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contacts"
                ],
                "summary": "Удалить контакт",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя, которого нужно удалить из контактов",
                        "name": "contact_user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Контакт успешно удален",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseDeleteContactSuccessForSwagger"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID контакта",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Контакт не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/profile/me": {
            "get": {
                "description": "Получение собственного профиля пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Получение профиля пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseGetProfileSuccessForSwagger"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутреняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/profile/{id}": {
            "get": {
                "description": "Получение собственного профиля пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Получение собственного профиля пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseGetProfileSuccessForSwagger"
                        }
                    },
                    "400": {
                        "description": "Невалидный формат json",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутреняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/profiles/me/avatar": {
            "patch": {
                "description": "Загружает новый аватар текущего пользователя",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Обновление аватара пользователя",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Файл аватара (image/jpeg|image/jpg|image/png|image/webp|image/gif), до 5MB",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseUpdateProfileForSwagger"
                        }
                    },
                    "400": {
                        "description": "Некорректный файл аватара",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутреняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/profiles/me/bio": {
            "patch": {
                "description": "Обновляет bio текущего авторизованного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Обновление bio пользователя",
                "parameters": [
                    {
                        "description": "Запрос на обновление био (поле bio)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_profile.RequestUpdateBio"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseUpdateProfileForSwagger"
                        }
                    },
                    "400": {
                        "description": "Невалидный json или bio не может быть пустым",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "ERROR_CODE"
                },
                "message": {
                    "type": "string",
                    "example": "Error message"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ApiError"
                    }
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus"
                        }
                    ],
                    "example": "error"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseCreateChatSuccessForSwagger": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_chat.ChatInformationDTO"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseCreateContactSuccessForSwagger": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_contacts.ContactResponse"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseDeleteContactSuccessForSwagger": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseGetChatByIDSuccessForSwagger": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_chat.ChatInformationDTO"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseGetChatsSuccessForSwagger": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_chat.ChatInformationDTO"
                    }
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseGetContactsSuccessForSwagger": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_contacts.ContactResponse"
                    }
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseGetProfileSuccessForSwagger": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_profile.ResponseGetProfile"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseLoginSuccessForSwagger": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_auth.ResponseLoginSuccess"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseLogoutSuccessForSwagger": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_auth.ResponseLogoutSuccess"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseRegisterSuccessForSwagger": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_auth.ResponseRegisterSuccess"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus": {
            "type": "string",
            "enum": [
                "success",
                "error"
            ],
            "x-enum-varnames": [
                "Success",
                "Error"
            ]
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseUpdateProfileForSwagger": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_profile.ResponseUpdateProfile"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_api.ResponseStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_auth.RequestLogin": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string",
                    "example": "user1"
                },
                "password": {
                    "type": "string",
                    "example": "passWo1d\u0026"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_auth.RequestRegistrate": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "testemail@dev.mail.ru"
                },
                "login": {
                    "type": "string",
                    "example": "user1"
                },
                "password": {
                    "type": "string",
                    "example": "passWo1d\u0026"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_auth.ResponseLoginSuccess": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string",
                    "example": "user1"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_auth.ResponseLogoutSuccess": {
            "type": "object"
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_auth.ResponseRegisterSuccess": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "testemail@dev.mail.ru"
                },
                "login": {
                    "type": "string",
                    "example": "user1"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_chat.ChatCreate": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "members_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Chat Title"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_chat.ChatType"
                        }
                    ],
                    "example": "Dialog"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_chat.ChatInformationDTO": {
            "type": "object",
            "properties": {
                "chat_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_chat.ChatType"
                        }
                    ],
                    "example": "dialog"
                },
                "id": {
                    "type": "integer"
                },
                "last_message": {
                    "$ref": "#/definitions/github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_chat.MessageDTO"
                },
                "title": {
                    "type": "string",
                    "example": "Chat Title"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_chat.ChatType": {
            "type": "string",
            "enum": [
                "dialog",
                "group",
                "channel"
            ],
            "x-enum-varnames": [
                "ChatTypeDialog",
                "ChatTypeGroup",
                "ChatTypeChannel"
            ]
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_chat.MessageDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00+09:00"
                },
                "sender_id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string",
                    "example": "Hello, my name is Artem"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_contacts.AddContactRequest": {
            "type": "object",
            "properties": {
                "contact_name": {
                    "type": "string"
                },
                "contact_user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_contacts.ContactResponse": {
            "type": "object",
            "properties": {
                "contact_name": {
                    "type": "string"
                },
                "contact_user_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_profile.RequestUpdateBio": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_profile.ResponseGetProfile": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "last_seen": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_go-park-mail-ru_2026_1_ASAP_internal_dto_profile.ResponseUpdateProfile": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "last_seen": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "pulseapp.space:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "API Pulse App",
	Description:      "API веб-приложения Pulse",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
