server:
  host: 0.0.0.0
  port: "8003"

s3:
  host: minio
  port: "9000"
  bucket: media
  use_ssl: false
  public_use_ssl: true
  public_host: pulseapp.space
  public_port: ""
  public_path: /

speechkit:
  lang: ru-RU

app:
  shutdown_seconds: 10
  log_level: info
