server:
  host: 0.0.0.0
  port: "8012"

postgres:
  host: db
  port: "5432"
  user: postgres
  db: asap

subscription:
  grpc_addr: subscription:8011

payment:
  secret_key: ""
  shop_id: ""
  return_url: "https://pulseapp.space/payment/return"

app:
  shutdown_seconds: 10
  log_level: info
