server:
  host: 0.0.0.0
  port: "8004"

ws_server:
  host: 0.0.0.0
  port: "8005"

postgres:
  host: db
  port: "5432"
  user: postgres
  db: asap

media:
  grpc_addr: "media:8003"

profile:
  grpc_addr: "profile:8002"

auth:
  grpc_addr: "auth:8001"

app:
  shutdown_seconds: 10
  log_level: info
