gateway_public_url: https://pulseapp.space

server:
  host: 0.0.0.0
  port: "8004"

ws_server:
  host: 0.0.0.0
  port: "8005"

postgres:
  host: db
  port: "5432"
  user: postgres
  db: asap

media:
  grpc_addr: "media:8003"

profile:
  grpc_addr: "profile:8002"

subscription:
  grpc_addr: "subscription:8011"

redis:
  host: redis
  port: "6379"
  database: 0

app:
  shutdown_seconds: 20
  log_level: info
