// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package complaint

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint(in *jlexer.Lexer, out *updateStatusRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "complaint_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ComplaintID = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint(out *jwriter.Writer, in updateStatusRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"complaint_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ComplaintID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v updateStatusRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v updateStatusRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *updateStatusRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *updateStatusRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint1(in *jlexer.Lexer, out *feedback) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "feedback_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeedbackName = string(in.String())
			}
		case "feedback_email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeedbackEmail = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint1(out *jwriter.Writer, in feedback) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"feedback_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.FeedbackName))
	}
	{
		const prefix string = ",\"feedback_email\":"
		out.RawString(prefix)
		out.String(string(in.FeedbackEmail))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v feedback) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v feedback) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *feedback) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *feedback) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint1(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint2(in *jlexer.Lexer, out *createComplaintRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "feedback":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Feedback).UnmarshalEasyJSON(in)
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint2(out *jwriter.Writer, in createComplaintRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"feedback\":"
		out.RawString(prefix)
		(in.Feedback).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v createComplaintRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v createComplaintRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *createComplaintRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *createComplaintRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint2(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint3(in *jlexer.Lexer, out *countTypeDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "count_type_bug":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountBug = int64(in.Int64())
			}
		case "count_type_upgrade":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountUpgrade = int64(in.Int64())
			}
		case "count_type_product":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountProduct = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint3(out *jwriter.Writer, in countTypeDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"count_type_bug\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.CountBug))
	}
	{
		const prefix string = ",\"count_type_upgrade\":"
		out.RawString(prefix)
		out.Int64(int64(in.CountUpgrade))
	}
	{
		const prefix string = ",\"count_type_product\":"
		out.RawString(prefix)
		out.Int64(int64(in.CountProduct))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v countTypeDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v countTypeDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *countTypeDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *countTypeDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint3(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint4(in *jlexer.Lexer, out *countStatusDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "count_status_opened":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountStatusOpened = int64(in.Int64())
			}
		case "count_status_in_work":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountStatusInWork = int64(in.Int64())
			}
		case "count_status_closed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountStatusClosed = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint4(out *jwriter.Writer, in countStatusDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"count_status_opened\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.CountStatusOpened))
	}
	{
		const prefix string = ",\"count_status_in_work\":"
		out.RawString(prefix)
		out.Int64(int64(in.CountStatusInWork))
	}
	{
		const prefix string = ",\"count_status_closed\":"
		out.RawString(prefix)
		out.Int64(int64(in.CountStatusClosed))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v countStatusDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v countStatusDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *countStatusDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *countStatusDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint4(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint5(in *jlexer.Lexer, out *complaintDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "feedback":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Feedback).UnmarshalEasyJSON(in)
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "attachment_url":
			if in.IsNull() {
				in.Skip()
				out.AttachmentURL = nil
			} else {
				if out.AttachmentURL == nil {
					out.AttachmentURL = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AttachmentURL = string(in.String())
				}
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UpdatedAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint5(out *jwriter.Writer, in complaintDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"feedback\":"
		out.RawString(prefix)
		(in.Feedback).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	if in.UserID != 0 {
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	if in.AttachmentURL != nil {
		const prefix string = ",\"attachment_url\":"
		out.RawString(prefix)
		out.String(string(*in.AttachmentURL))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.String(string(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v complaintDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v complaintDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *complaintDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *complaintDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint5(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint6(in *jlexer.Lexer, out *complaintAnalyticDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "count_status":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.CountStatus).UnmarshalEasyJSON(in)
			}
		case "count_type":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.CountType).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint6(out *jwriter.Writer, in complaintAnalyticDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"count_status\":"
		out.RawString(prefix[1:])
		(in.CountStatus).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"count_type\":"
		out.RawString(prefix)
		(in.CountType).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v complaintAnalyticDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v complaintAnalyticDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *complaintAnalyticDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *complaintAnalyticDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ASAPInternalGatewayComplaint6(l, v)
}
